require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'

# Disable problematic cops
Capybara/RSpec/PredicateMatcher:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 50
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Max: 40
  Exclude:
    - 'spec/**/*'
    - 'tapsilat.gemspec'

Metrics/ClassLength:
  Max: 400
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Metrics/ParameterLists:
  Max: 10

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/ExampleLength:
  Max: 50

RSpec/MultipleExpectations:
  Max: 25

RSpec/NestedGroups:
  Max: 4

Naming/PredicatePrefix:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

RSpec/IdenticalEqualityAssertion:
  Enabled: false 